version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: "${DB_HOST}"
            port: "${DB_PORT}"
            user: "${DB_USER}"
            password: "${DB_PASSWORD}"
  postgres:
    image: postgres:10.3
    container_name: postgres-10.3
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
